language: python
python:
    - "3.6"

services:
    - docker
env:
    - DEBUG="secrethub://roboticsjx/jx-django-api/DEBUG"
    - SECRET_KEY="secrethub://roboticsjx/jx-django-api/SECRET_KEY"
    - DJANGO_ALLOWED_HOSTS="secrethub://roboticsjx/jx-django-api/DJANGO_ALLOWED_HOSTS"
    - SQL_ENGINE="secrethub://roboticsjx/jx-django-api/SQL_ENGINE"
    - SQL_DATABASE="secrethub://roboticsjx/jx-django-api/SQL_DATABASE"
    - SQL_USER="secrethub://roboticsjx/jx-django-api/SQL_USER"
    - SQL_PASSWORD="secrethub://roboticsjx/jx-django-api/SQL_PASSWORD"
    - SQL_HOST="secrethub://roboticsjx/jx-django-api/SQL_HOST"
    - SQL_PORT="secrethub://roboticsjx/jx-django-api/SQL_PORT"
    - DATABASE="secrethub://roboticsjx/jx-django-api/DATABASE"
    - DB_HOST="secrethub://roboticsjx/jx-django-api/DB_HOST"
    - DB_NAME="secrethub://roboticsjx/jx-django-api/DB_NAME"
    - DB_USER="secrethub://roboticsjx/jx-django-api/DB_USER"
    - DB_PASS="secrethub://roboticsjx/jx-django-api/DB_PASS"

before_script: pip install docker-compose


script:
    - docker-compose run app sh -c "python manage.py test && flake8"