# A project that creates a FOOD Recipes API
# It's a Learning project
# warning manage runserver  is for develop mode only
# encrypt to postgres_password not a good idea push that info
version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
